### ISSUE TITLE
cannot reset figure and do lasso selection

### ISSUE THREAD

**Issue by iiiir** [neuhausi/single-cell-viewer#2]
Hi Isaac,

We are implementing SCV as our internal solution, and develop on top of it.

It kind of worked "out-of-box", with some minor issues mainly related to the DE gene tab.
basically:
1. the cluster selection will not be able to reset/re-select after the first selection. hit ESC also does not reset the plot.

2. selecting "lasso" selection does not trigger any response.

![image](https://user-images.githubusercontent.com/4137873/68917983-56374780-0721-11ea-873c-ad5dbe51d2c6.png)

3. at the dotplot tab, the plot will not show up for me
![image](https://user-images.githubusercontent.com/4137873/68918130-ca71eb00-0721-11ea-8ddc-c0efb2067904.png)

The browser is google Chrome and the SCV server has:
> CentOS Linux release 7.3.1611 (Core) 
> R-3.5.3
> packageVersion("periscope")
[1] ‘0.4.6’
> packageVersion("canvasXpress")
[1] ‘1.25.0’

Thanks!
Shuoguo

**Comment by neuhausi** [comment]
Can you please check if there are any errors in the JavaScript Console. It would be great if you can include the image using the camera icon.
Regards,
Isaac

**Comment by iiiir** [comment]
I start the application in R console -- not sure how to monitor in javascript console...
here is the R console screenshot:
![image](https://user-images.githubusercontent.com/4137873/68961200-b2808280-0786-11ea-9c2b-2cb9af035717.png)

There seems to be a log file, but I couldn't locate it.

Thanks,
Shuoguo

**Comment by neuhausi** [comment]
Use chrome. Right click and select 'Inspect' click on the 'console' tab and paste the content of that tab. I will be able to see if there are any errors. BTW, the periscope example gives no errors. http://www.canvasxpress.org:3838/scv_tirosh/

**Comment by iiiir** [comment]
The error message for dotplot were shown.
![image](https://user-images.githubusercontent.com/4137873/68969541-0d6fa500-079a-11ea-82c5-f4f948065797.png)

For the DE tab, looks like if I choose different cluster, it does not refresh the plots and does not update the console.
Unlike the periscope example, it will say: "data ready - afterRender"

**Comment by iiiir** [comment]
Also, if i check/un-check the side bar filter:
![image](https://user-images.githubusercontent.com/4137873/68969872-d2ba3c80-079a-11ea-8fee-28ba62b76f82.png)

It does not trigger command:
![image](https://user-images.githubusercontent.com/4137873/68969920-f54c5580-079a-11ea-8ab9-13b8014fc34c.png)

while the periscope example will immediately have updates in the console:
![image](https://user-images.githubusercontent.com/4137873/68969966-0f863380-079b-11ea-9747-9509be9293ed.png)

Shuoguo

**Comment by neuhausi** [comment]
That seems to be a n error in the htmlwidgets package. (Perhaps Connie can help with that). Just curious, would you mind clicking in the last arrow to see were the problem started.
Thank you.
Isaac

**Comment by neuhausi** [comment]
Please see this issue.
Thank you.
isaac

**Comment by cb4ds** [comment]
Please run a fresh session of the app after a restart of R and then post the results of sessionInfo().  Also confirm that it is the latest version of code from this repository.

**Comment by iiiir** [comment]
Here is the details for the dotplot error:
![image](https://user-images.githubusercontent.com/4137873/68981534-95fd3e00-07b8-11ea-952c-89c3582f21d6.png)

R sessioninfo for fresh start of SCV:

![image](https://user-images.githubusercontent.com/4137873/68982096-7ebf5000-07ba-11ea-867d-03db5038511b.png)


> > sessionInfo()
> R version 3.5.3 (2019-03-11)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS: /R/rh7/R-3.5.3/lib64/R/lib/libRblas.so
> LAPACK: /R/rh7/R-3.5.3/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> other attached packages:
>  [1] Seurat_3.0.1         RColorBrewer_1.1-2   tidyr_0.8.3
>  [4] tibble_2.1.3         dplyr_0.8.1          logging_0.10-108
>  [7] shinyjs_1.0          shinydashboard_0.7.1 pbapply_1.4-1
> [10] htmlwidgets_1.3      future_1.14.0        canvasXpress_1.25.0
> [13] shinyBS_0.61         periscope_0.4.6      shiny_1.3.2
> 
> loaded via a namespace (and not attached):
>  [1] tsne_0.1-3          nlme_3.1-139        bitops_1.0-6
>  [4] httr_1.4.1          sctransform_0.2.0   tools_3.5.3
>  [7] R6_2.4.0            irlba_2.3.3         DT_0.8
> [10] KernSmooth_2.23-15  lazyeval_0.2.2      colorspace_1.4-1
> [13] npsurv_0.4-0        gridExtra_2.3       tidyselect_0.2.5
> [16] compiler_3.5.3      plotly_4.9.0        caTools_1.17.1.2
> [19] scales_1.0.0        lmtest_0.9-37       ggridges_0.5.1
> [22] stringr_1.4.0       digest_0.6.20       R.utils_2.9.0
> [25] pkgconfig_2.0.2     htmltools_0.3.6     bibtex_0.4.2
> [28] rlang_0.4.1         zoo_1.8-6           jsonlite_1.6
> [31] crosstalk_1.0.0     ica_1.0-2           gtools_3.8.1
> [34] R.oo_1.22.0         magrittr_1.5        Matrix_1.2-17
> [37] Rcpp_1.0.2          munsell_0.5.0       reticulate_1.12
> [40] ape_5.3             R.methodsS3_1.7.1   stringi_1.4.3
> [43] yaml_2.2.0          gbRd_0.4-11         MASS_7.3-51.4
> [46] gplots_3.0.1.1      Rtsne_0.15          plyr_1.8.4
> [49] grid_3.5.3          parallel_3.5.3      gdata_2.18.0
> [52] listenv_0.7.0       promises_1.0.1      ggrepel_0.8.1
> [55] crayon_1.3.4        lattice_0.20-38     cowplot_1.0.0
> [58] splines_3.5.3       SDMTools_1.1-221.1  pillar_1.4.2
> [61] igraph_1.2.4.1      reshape2_1.4.3      future.apply_1.3.0
> [64] codetools_0.2-16    glue_1.3.1          lsei_1.2-0
> [67] metap_1.1           data.table_1.12.2   png_0.1-7
> [70] httpuv_1.5.1        Rdpack_0.11-0       gtable_0.3.0
> [73] RANN_2.6.1          purrr_0.3.2         assertthat_0.2.1
> [76] ggplot2_3.2.1       rsvd_1.0.2          mime_0.7
> [79] xtable_1.8-4        later_0.8.0         survival_2.44-1.1
> [82] viridisLite_0.3.0   cluster_2.0.9       globals_0.12.4
> [85] fitdistrplus_1.0-14 ROCR_1.0-7


Thank!
Shuoguo

**Comment by cb4ds** [comment]
I am unable to reproduce the issues.  The code from the master branch works out of the box in R 3.5.3, and package versions matching what you have posted - with one exception.  The latest posted version of CanvasXpress to CRAN is 1.24.8.  Please reinstall canvasXpress from CRAN and try again.  Non-CRAN CX versions may not work and haven't undergone full testing.
<img width="1339" alt="Screen Shot 2019-11-18 at 3 49 42 PM" src="https://user-images.githubusercontent.com/9085025/69104029-e1fbed00-0a1b-11ea-83bb-db862c327f11.png">
<img width="918" alt="Screen Shot 2019-11-18 at 3 52 21 PM" src="https://user-images.githubusercontent.com/9085025/69104040-e58f7400-0a1b-11ea-88be-922428f66822.png">

**Comment by iiiir** [comment]
CanvasXpress 1.24.8 solved the issue! Now fully functional.
I only have issue on my windows 10 machine to select cells for DE gene analysis (both chrome and firefox), something to do with my windows machine security that I have not figured out the reason. 
But I am **able select** cells on a centOS machine.

**Comment by neuhausi** [comment]
Glad to hear that!
