### ISSUE TITLE
bioconductor repo error with non-bioconductor Seurat package

### ISSUE THREAD

**Issue by pcantalupo** [neuhausi/single-cell-viewer#3]
Is this a rsconnect issue or a single-cell-viewer issue?
https://github.com/rstudio/rsconnect/issues/399

Please advise on how to publish SCV to shinyapps

Thank you

**Comment by cb4ds** [comment]
see this thread please https://github.com/rstudio/rsconnect/issues/399 - this is not a single-cell-viewer issue.
