### ISSUE TITLE
Issue when compiling and running the sample data

### ISSUE THREAD

**Issue by galvaniquee** [neuhausi/single-cell-viewer#4]
Hi,

I ran into two issues when compiling and running the sample data:

1. When running tirosh_pipeline.R with the data downloaded from the Broad, I found this error when running the code in "set cell ident".

`cell_ident <- droplevels(df.ident$Cluster)`
`Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character"`

So I skipped this line and ran:
`cell_ident <- df.ident$Cluster`

2. The remaining code seems fine and I could save the RDS for shinyapp. However, when running shinyapp I got into this error:

`Warning: Error in <Anonymous>: unable to find an inherited method for function ‘select’ for signature ‘"data.frame"’
  97: %>%
  96: get_overview_plot [program/fxn/supporting_plots.R#10]
  95: func [program/server_local.R#363]
  82: origRenderFunc
  81: output$cxOverviewPlot
   1: shiny::runApp
Warning: Error in rename: unused argument (avg_logFC = avg_logfc)
  64: get_top_genes_data [program/fxn/supporting_misc.R#85]
  63: <reactive:top10_genes> [program/server_local.R#142]
  47: <Anonymous>
  45: lapply
  44: <observer>
   1: shiny::runApp
Warning: Error in rename: unused argument (avg_logFC = avg_logfc)
  47: <Anonymous>`

I checked and it seems like the name of the variable is incorrect - avg_logFC instead of avg_logfc in supporting_misc.R #85. I modified it and there comes another error:

`Warning: Error in rename: unused arguments (Gene = gene, Cluster = cluster)
  63: %>%
  62: get_top_genes_data [program/fxn/supporting_misc.R#88]
  61: <reactive:top10_genes> [program/server_local.R#142]
  45: tabledata
  44: <observer>
   1: shiny::runApp
Warning: Error in rename: unused arguments (Gene = gene, Cluster = cluster)
  49: <Anonymous>
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘select’ for signature ‘"data.frame"’
  97: %>%
  96: get_overview_plot [program/fxn/supporting_plots.R#10]
  95: func [program/server_local.R#363]
  82: origRenderFunc
  81: output$cxOverviewPlot
   1: shiny::runApp`

I am hoping to be able to compile your sample data right such that I could visualize my own data as the next step. Let me know what you think.

I am running in Docker:
- R version 4.0.2
- Shiny 1.5.0
- Seurat 3.2.2

**Comment by galvaniquee** [comment]
Hi,

Just a quick update. It seems like I have fixed issue 2 now. However, issue 1 still exists, and it seems to be leading to another error when I was trying to visualize heatmap by top DE genes. I got this error - "Row names in varAnnot are different from row names in data"

`Warning: Error in setup_z: Row names in varAnnot are different from row names in data
  100: stop
   99: setup_z
   98: canvasXpress
   97: get_heatmap_plot [program/fxn/supporting_plots.R#293]
   96: renderUI [program/server_local.R#430]
   95: func
   82: origRenderFunc
   81: output$cxHeatmapPlot
    1: shiny::runApp`

Let me know what you think, thanks!

**Comment by iiiir** [comment]
Hi,
Instead of running `cell_ident <- droplevels(df.ident$Cluster)`, can you replace with `cell_ident <- factor(df.ident$Cluster)`?

I noticed that you are using R 4.0, is this your preferred R version?

Thanks,
Shuoguo

**Comment by galvaniquee** [comment]
Hi Shuoguo,

Thanks for the response! Yes I am using R 4.0, do you suggest me to use another version of R? I tried cell_ident <- factor(df.ident$Cluster) in tirosh_pipeline.R. However, it's still giving the same error "Row names in varAnnot are different from row names in data" when I tried to visualize the heatmap. It seems to be related to the line 293 of supporting_plots.R, after assigning varAnnot with data. Do you have any idea on how to update this?

`Warning: Error in setup_z: Row names in varAnnot are different from row names in data
  100: stop
   99: setup_z
   98: canvasXpress
   97: get_heatmap_plot [program/fxn/supporting_plots.R#293]
   96: renderUI [program/server_local.R#430]
   95: func
   82: origRenderFunc
   81: output$cxHeatmapPlot
    1: shiny::runApp`

**Comment by iiiir** [comment]
I just tested the following script worked for me:
[tirosh_for_scv.pdf](https://github.com/neuhausi/single-cell-viewer/files/5732097/tirosh_for_scv.pdf)

**Comment by galvaniquee** [comment]
Hi Shuoguo,

Thanks for running it! 
I guess I haven't made myself clear, I got the error after running Shiny::runApp('shiny_app'). I can see the cluster overview, dot plot and so, except for heat map. When i try to generate heat map i got the error mentioned above - "Row names in varAnnot are different from row names in data". That's what I am trying to debug at the moment. 

I will try get a R 3.6.3 docker image and see if it's a version issue as well. Let me know what you think.

**Comment by galvaniquee** [comment]
Hi Shuoguo,

Just a quick update, I switched to a R3.6.3 docker and the error goes away. Now it's working like a charm. Thanks again for your help!

**Comment by iiiir** [comment]
Good to hear that!
