### ISSUE TITLE
Auto-load data upon starting the viewer

### ISSUE THREAD

**Issue by galvaniquee** [neuhausi/single-cell-viewer#5]
Hi Shuoguo,

Hope all is well and happy holidays! I have one question about loading the data to the viewer, is there any version of SCV that can automatically preload a dataset from a destinated folder? Or how would you suggest me to edit the code to allow that to happen? Let me know and thanks.

**Comment by cb4ds** [comment]
Hi!  The application uses the periscope framework so all the "regular" shiny files are organized under the /program folder.  You'll find the data load function in fxn/supporting_data.R and you can change the functionality to meet your needs there!  Best wishes!
