### ISSUE TITLE
RDS file larger than 10 MB.

### ISSUE THREAD

**Issue by mdidish** [neuhausi/single-cell-viewer#6]
Hi
Thank you for this shiny app.
I would work with my own data, which have all required slots. But when I try to load it, I have this message:
`The file you have selected is larger than 10 MB. It is now being uploaded and will load momentarily.`
And then `Maximum upload size exceeded` appeared below the Load button, and the dataset is not loaded.

Have you tricks to decrease tha size of the RDS file? My file is currently around 600MB.

Best,
Marc

**Comment by cb4ds** [comment]
Removing unused assays and processing steps will help reduce the size of the Seurat object significantly.  We have also had good success using [DietSeurat](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/DietSeurat) in the Seurat package to reduce sizes significantly.  Best Wishes!

**Comment by mdidish** [comment]
ok thank you for this response.
